version: 2

jobs:
  build:
    working_directory: ~/comms-platform
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers

    steps:
      - checkout

      - run: sudo apt-get install -y ruby ruby-dev
      
      - run: sudo gem install jekyll
      
      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ .Revision }}
            - deps-{{ .Branch }}
            - deps
            
      - run: sbt update
      
      - save_cache:
          key: deps-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/.ivy2"
            - "~/.sbt"
            - "target/resolution-cache"
            - "project/target/resolution-cache"
      
      - run: sbt makeMicrosite

      - deploy:
          name: Deploy if master branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" -a "${CIRCLE_PROJECT_USERNAME}" == "ovotech" ]; then
              git config --global user.email "hello.comms@ovoenergy.com"
              git config --global user.name "OVO Comms CircleCI"
              git config --global push.default simple
              sbt publishMicrosite
            fi

experimental:
  notify:
    branches:
      only:
        - master
